[package]
name = "demo"
version = "1.0.0"
edition = "2024"

[dependencies]
framework.workspace = true
framework_validator.workspace = true

tracing.workspace = true
serde.workspace = true
chrono.workspace = true
tokio.workspace = true
axum.workspace = true

bytes = "*"
tokio-util = "*"
tokio-stream = "*"
futures = "*"
