[package]
name = "log_exporter"
version = "0.3.6"
edition = "2024"

[dependencies]
framework.workspace = true

tracing.workspace = true
serde.workspace = true
chrono.workspace = true
tokio.workspace = true
axum.workspace = true

hostname = "*"
sha2 = "*"
