[package]
name = "log_processor"
version = "0.3.9"
edition = "2024"

[dependencies]
framework.workspace = true

tracing.workspace = true
serde.workspace = true
chrono.workspace = true
tokio.workspace = true
axum.workspace = true
regex = "*"
